name: Car Scraper and Analysis

on:
  workflow_dispatch:
    # Permitir ejecución manual

jobs:
  scrape-and-analyze:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          playwright install chromium

      - name: Cache car data
        uses: actions/cache@v4
        with:
          path: ./data
          key: car-data-${{ github.ref }}-${{ github.run_number }}
          restore-keys: |
            car-data-${{ github.ref }}-
            car-data-

      - name: Create data directory
        run: mkdir -p data

      - name: Run car scraping
        env:
          ARCHIVO_COCHES: "./data/coches.json"
          ARCHIVO_COCHES_ELIMINADO: "./data/coches_eliminados.json"
          URL_LISTADO: ${{ secrets.URL_LISTADO }}
        run: python scrapping_cars.py

      - name: Run car analysis
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          ARCHIVO_COCHES: "./data/coches.json"
          OPENAI_MODEL_ANALISIS: "gpt-4o-mini"
        run: python ask_openai_car_evaluation.py

      - name: Send email with analysis
        env:
          GMAIL_USER: automatiramos@gmail.com
          GMAIL_PASSWORD: ${{ secrets.GMAIL_PASSWORD }}
          EMAIL_DESTINATARIO: josselynmishellramosacaro@gmail.com
        run: python send_email.py
